const kittens = [
	{ key: "Abby", link: 'https://placekitten.com/200/200' },
	{ key: "Angel", link: 'https://placekitten.com/200/201' },
	{ key: "Annie", link: 'https://placekitten.com/200/202' },
	{ key: "Baby", link: 'https://placekitten.com/200/203' },
	{ key: "Bailey", link: 'https://placekitten.com/200/204' },
	{ key: "Bandit", link: 'https://placekitten.com/200/205' },
	{ key: "Bear", link: 'https://placekitten.com/200/206' },
	{ key: "Bella", link: 'https://placekitten.com/200/207' },
	{ key: "Bob", link: 'https://placekitten.com/200/208' },
	{ key: "Boo", link: 'https://placekitten.com/200/209' },
	{ key: "Boots", link: 'https://placekitten.com/200/210' },
	{ key: "Bubba", link: 'https://placekitten.com/200/211' },
	{ key: "Buddy", link: 'https://placekitten.com/200/212' },
	{ key: "Buster", link: 'https://placekitten.com/200/213' },
	{ key: "Cali", link: 'https://placekitten.com/200/214' },
	{ key: "Callie", link: 'https://placekitten.com/200/215' },
	{ key: "Casper", link: 'https://placekitten.com/200/216' },
	{ key: "Charlie", link: 'https://placekitten.com/200/217' },
	{ key: "Chester", link: 'https://placekitten.com/200/218' },
	{ key: "Chloe", link: 'https://placekitten.com/200/219' },
	{ key: "Cleo", link: 'https://placekitten.com/200/220' },
	{ key: "Coco", link: 'https://placekitten.com/200/221' },
	{ key: "Cookie", link: 'https://placekitten.com/200/222' },
	{ key: "Cuddles", link: 'https://placekitten.com/200/223' },
	{ key: "Daisy", link: 'https://placekitten.com/200/224' },
	{ key: "Dusty", link: 'https://placekitten.com/200/225' },
	{ key: "Felix", link: 'https://placekitten.com/200/226' },
	{ key: "Fluffy", link: 'https://placekitten.com/200/227' },
	{ key: "Garfield", link: 'https://placekitten.com/200/228' },
	{ key: "George", link: 'https://placekitten.com/200/229' },
	{ key: "Ginger", link: 'https://placekitten.com/200/230' },
	{ key: "Gizmo", link: 'https://placekitten.com/200/231' },
	{ key: "Gracie", link: 'https://placekitten.com/200/232' },
	{ key: "Harley", link: 'https://placekitten.com/200/233' },
	{ key: "Jack", link: 'https://placekitten.com/200/234' },
	{ key: "Jasmine", link: 'https://placekitten.com/200/235' },
	{ key: "Jasper", link: 'https://placekitten.com/200/236' },
	{ key: "Kiki", link: 'https://placekitten.com/200/237' },
	{ key: "Kitty", link: 'https://placekitten.com/200/238' },
	{ key: "Leo", link: 'https://placekitten.com/200/239' },
	{ key: "Lilly", link: 'https://placekitten.com/200/240' },
	{ key: "Lily", link: 'https://placekitten.com/200/241' },
	{ key: "Loki", link: 'https://placekitten.com/200/242' },
	{ key: "Lola", link: 'https://placekitten.com/200/243' },
	{ key: "Lucky", link: 'https://placekitten.com/200/244' },
	{ key: "Lucy", link: 'https://placekitten.com/200/245' },
	{ key: "Luna", link: 'https://placekitten.com/200/246' },
	{ key: "Maggie", link: 'https://placekitten.com/200/247' },
	{ key: "Max", link: 'https://placekitten.com/200/248' },
	{ key: "Mia", link: 'https://placekitten.com/200/249' },
	{ key: "Midnight", link: 'https://placekitten.com/201/200' },
	{ key: "Milo", link: 'https://placekitten.com/202/200' },
	{ key: "Mimi", link: 'https://placekitten.com/203/200' },
	{ key: "Miss kitty", link: 'https://placekitten.com/204/200' },
	{ key: "Missy", link: 'https://placekitten.com/205/200' },
	{ key: "Misty", link: 'https://placekitten.com/206/200' },
	{ key: "Mittens", link: 'https://placekitten.com/207/200' },
	{ key: "Molly", link: 'https://placekitten.com/208/200' },
	{ key: "Muffin", link: 'https://placekitten.com/209/200' },
	{ key: "Nala", link: 'https://placekitten.com/210/200' },
	{ key: "Oliver", link: 'https://placekitten.com/211/200' },
	{ key: "Oreo", link: 'https://placekitten.com/212/200' },
	{ key: "Oscar", link: 'https://placekitten.com/213/200' },
	{ key: "Patches", link: 'https://placekitten.com/214/200' },
	{ key: "Peanut", link: 'https://placekitten.com/215/200' },
	{ key: "Pepper", link: 'https://placekitten.com/216/200' },
	{ key: "Precio", link: 'https://placekitten.com/217/200' },
	{ key: "Prince", link: 'https://placekitten.com/218/200' },
	{ key: "Pumpki", link: 'https://placekitten.com/219/200' },
	{ key: "Rascal", link: 'https://placekitten.com/220/200' },
	{ key: "Rocky", link: 'https://placekitten.com/221/200' },
	{ key: "Sadie", link: 'https://placekitten.com/222/200' },
	{ key: "Salem", link: 'https://placekitten.com/223/200' },
	{ key: "Sam", link: 'https://placekitten.com/224/200' },
	{ key: "Samant", link: 'https://placekitten.com/225/200' },
	{ key: "Sammy", link: 'https://placekitten.com/226/200' },
	{ key: "Sasha", link: 'https://placekitten.com/227/200' },
	{ key: "Sassy", link: 'https://placekitten.com/228/200' },
	{ key: "Scoote", link: 'https://placekitten.com/229/200' },
	{ key: "Shadow", link: 'https://placekitten.com/230/200' },
	{ key: "Sheba", link: 'https://placekitten.com/231/200' },
	{ key: "Simba", link: 'https://placekitten.com/232/200' },
	{ key: "Simon", link: 'https://placekitten.com/233/200' },
	{ key: "Smokey", link: 'https://placekitten.com/234/200' },
	{ key: "Snicke", link: 'https://placekitten.com/235/200' },
	{ key: "Snowba", link: 'https://placekitten.com/236/200' },
	{ key: "Snuggl", link: 'https://placekitten.com/237/200' },
	{ key: "Socks", link: 'https://placekitten.com/238/200' },
	{ key: "Sophie", link: 'https://placekitten.com/239/200' },
	{ key: "Spooky", link: 'https://placekitten.com/240/200' },
	{ key: "Sugar", link: 'https://placekitten.com/241/200' },
	{ key: "Tiger", link: 'https://placekitten.com/242/200' },
	{ key: "Tigger", link: 'https://placekitten.com/243/200' },
	{ key: "Tinker", link: 'https://placekitten.com/244/200' },
	{ key: "Toby", link: 'https://placekitten.com/245/200' },
	{ key: "Troubl", link: 'https://placekitten.com/246/200' },
	{ key: "Whiske", link: 'https://placekitten.com/247/200' },
	{ key: "Willow", link: 'https://placekitten.com/248/200' },
	{ key: "Zoe", link: 'https://placekitten.com/249/200' },
	{ key: "Zoey",  link: 'https://placekitten.com/250/200' }
];

const loreIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit." + 
" Vivamus eget sapien et enim interdum vehicula. Mauris vehicula" +
" tortor porta, ornare est a, molestie orci. Donec eleifend, nunc" +
" ac posuere vulputate. " +
"Lorem ipsum dolor sit amet, consectetur adipiscing elit." + 
" Vivamus eget sapien et enim interdum vehicula. Mauris vehicula" +
" tortor porta, ornare est a, molestie orci. Donec eleifend, nunc" +
" ac posuere vulputate. " +
"Lorem ipsum dolor sit amet, consectetur adipiscing elit." + 
" Vivamus eget sapien et enim interdum vehicula. Mauris vehicula" +
" tortor porta, ornare est a, molestie orci. Donec eleifend, nunc" +
" ac posuere vulputate. " 



export { kittens, loreIpsum };   